use_frameworks!

platform :ios, '8.0'

target 'MZCMEditor_Example' do
  pod 'MZCMEditor', :path => '../'

  target 'MZCMEditor_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
